### ISSUE TITLE
Dust off easybread

### ISSUE THREAD

**Issue by wreiske** [easybread/easybread#115]
- [x] Update all dependencies
- [x] Target node 20
- [x] Migrate to Nx
- [x] Fix TS errors
- [x] Setup CI
- [x] migrate to nx
- [x] reimplement data-mapper package
- [x] refactor the code 
- [x] #144
- [x] Rename gsuite adapter to google-admin or google-workspaces 
- [x] Ensure at least google-admin (google-workspaces) adapter package is working correctly
- [x] Publish release to npm

**Comment by alexandr2110pro** [comment]
@wreiske 

We also need to:
- migrate to a more modern monorepo tool. We can just migrate to the latest lerna (must be relatively easy), but it might be better to go with pure nx (lerna is now using nx under the hood)
- go through old tickets and figure out what we are going to do with them (this looks like a separate task)
