### ISSUE TITLE
Create an example plugin with the structure required to start communicating with HR products using easybread APIs

### ISSUE THREAD

**Issue by wreiske** [easybread/easybread#3]
While working on the core easybread module and APIs, keep the example plugin up-to-date with any API changes you make before MVP.

We should have a pretty solid understanding of what the final APIs and structure will be before we launch to NPM so we don't have to have too many breaking changes to the way easybread plugins work in the future.

The example plugin should be well documented and be the base for any new plugins (e.g. adp, bamboohr, etc.). Essentially, anyone should be able to fork the plugin repository and get started writing the HR specific code within the plugin.

**Comment by alexandr2110pro** [comment]
See
https://github.com/easybread/easybread.service-adapter-example
